#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sirius.Resource", IsApplication=true)]

namespace Sirius
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int civ_fill_color = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int ColorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int ColorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ColorPrimaryDark = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_bord = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_amigo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_companheiro = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_excursionista = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_fechar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_geral = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_guia = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_pesquisador = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_pioneiro = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int perfil = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int round_corner = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Sirius_logo_semfundo = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int NomeTextView = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int circleMenu1 = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int fotoPerfil2 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnoBiblico = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
